global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "pdf-rag"

    static_configs:
      - targets:
          - backend:8000

remote_write:
  - url: https://prometheus-prod-43-prod-ap-south-1.grafana.net/api/prom/push

    basic_auth:
      username: "3337260"

      password: $PROMETHEUS_PASSWORD